server:
  port: 8085
spring:
  application:
    name: Product-Load
  batch:
    job:
      enabled: false
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:localhost;DB_CLOSE_ON_EXIT=FALSE
    username: admin
    password:
imports:
  csv:
    folder: ./import-folder
integration:
  product.url:  http://localhost:8081
  price.url:  http://localhost:8082
  inventory.url:  http://localhost:8083
